id: app.example
version: 0.1.0
name: Example OKHAM App
summary: Minimal OKHAM app package template

# Required: stable namespace prefix for all contract ids in this app package.
# Example: app.okham.todo
namespace: app.example

# Informative: declare goals and boundaries here.
goals:
  - Describe the application as contracts (meaning) not implementation.
non_goals:
  - Specify runtime details (cloud, transport, languages).

actors:
  - id: user
    description: End user

notes:
  - Runtime/tech bindings belong in bindings/ or deploy/.
